FROM python:3.9-slim

RUN apt-get update && apt-get install -y wget curl && rm -rf /var/lib/apt/lists/*

RUN useradd -m appuser
WORKDIR /app
COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY backend .
RUN chown -R appuser:appuser /app
USER appuser

CMD ["python", "app.py"]
