apiVersion: v2
name: bookshelf-app
description: A Helm chart for My Bookshelf backend and database
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 16.7.4
    repository: https://charts.bitnami.com/bitnami