apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookshelf-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'git@gitlab.com:maxopsdeveleap/my-bookshelf-gitops.git'
    targetRevision: main
    path: bookshelf-app     
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: bookshelf-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
