apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: efk
    server: https://kubernetes.default.svc
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.45.0
    helm:
      releaseName: fluent-bit
      values: |
        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush 5
                Log_Level info
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port 2020
                storage.path /var/log/flb-storage/
                storage.sync normal
                storage.checksum off
                storage.backlog.mem_limit 50M
          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/*.log
                Tag kube.*
                Skip_Long_Lines On
                Skip_Empty_Lines On
                Parser docker
                DB /var/log/flb_kube.db
                Mem_Buf_Limit 50MB
                Buffer_Chunk_Size 32k
                Buffer_Max_Size 256k
                Refresh_Interval 10
          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Kube_Tag_Prefix kube.var.log.containers.
                Merge_Log On
                Keep_Log Off
                K8S-Logging.Parser On
                K8S-Logging.Exclude On
                Annotations Off
                Labels On
          outputs: |
            [OUTPUT]
                Name es
                Match kube.*
                Host elasticsearch-master
                Port 9200
                Index kubernetes
                HTTP_User elastic
                HTTP_Passwd b7syQrF2DVfArlTB
                tls Off
                tls.verify Off
                Suppress_Type_Name On
                Logstash_Format On
                Logstash_Prefix kubernetes
                Logstash_DateFormat %Y.%m.%d
                Replace_Dots On
                Retry_Limit 2
                workers 1
        tolerations:
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
          - operator: "Exists"
            effect: "NoExecute"
          - operator: "Exists"
            effect: "NoSchedule"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true