apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: efk
    server: https://kubernetes.default.svc
  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: 7.17.3
    helm:
      releaseName: kibana
      values: |
        elasticsearchHosts: "http://elasticsearch-master:9200"
        service:
          type: ClusterIP
        
        # Resource limits for Kibana
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        
        # Health check configuration
        healthCheckPath: "/app/kibana"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true